/*
 * generated by Xtext
 */
package br.ufpe.cin.test;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TestRuntimeModule extends br.ufpe.cin.test.AbstractTestRuntimeModule {

}
